apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
spec:
  rules:
  - host: a.mancuso.my.kube.um.edu.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kb-metabase
            port:
              number: 80
