apiVersion: v1
kind: Secret
metadata:
  name: metabase-secret
type: Opaque
data:
  MB_DB_USER: bWV0YWJhc2U=
  MB_DB_PASS: cGFzc3dvcmQ=
  ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  ADMIN_PASSWORD: U3VwZXJTZWN1cmVQYXNzd29yZDEyMyE=
  METABASE_PASSWORD: U3VwZXJTZWN1cmVQYXNzd29yZDEyMyE=